[package]
name = "configurator"
version = "0.1.0"
authors = ["Hiram Silvey <hello@iamhiram.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
json = "0.12.4"